const $=s=>document.querySelector(s);let player=null,isGuest=true,battle=null;
const U={ranger:{name:'Ranger',icon:'⌁',d:90,r:175,rate:.72,cost:150,text:'Fast single-target defender.'},cannon:{name:'Cannon',icon:'◉',d:190,r:145,rate:1.35,cost:300,text:'Heavy splash damage.'}};
const C={kendrick:{name:'Kendrick the Drake',icon:'♛',d:400,r:220,text:'NULLIFY reveals hidden targets. TOTAL ANNIHILATION scales with deployed allies. PERFECT COMBO lasts 30 seconds.',abs:[['annihilation','TOTAL ANNIHILATION'],['combo','PERFECT COMBO']]},spirit:{name:'Spirit Devourer',icon:'◈',d:300,r:190,text:'Suffocation Aura weakens enemies. Attacks reveal hidden enemies and collect souls. Idle Transfiguration creates a 20-second domain.',abs:[['transfiguration','IDLE TRANSFIGURATION'],['puppeteer','PUPPETEER']]}};
const E={grunt:{name:'Grunt',hp:110,sp:52,rew:18},runner:{name:'Runner',hp:70,sp:88,rew:22},brute:{name:'Brute',hp:430,sp:32,rew:55,arm:25},wraith:{name:'Wraith',hp:170,sp:66,rew:40,inv:true},medic:{name:'Hex Medic',hp:210,sp:44,rew:48,heal:true},splitter:{name:'Splitter',hp:280,sp:48,rew:60,split:true},summoner:{name:'Rift Summoner',hp:360,sp:37,rew:75,sum:true},elite:{name:'Elite',hp:900,sp:40,rew:150,arm:35}};
const path=[{x:70,y:110},{x:270,y:110},{x:270,y:300},{x:520,y:300},{x:520,y:150},{x:790,y:150},{x:790,y:480},{x:1010,y:480}],slots=[{x:145,y:205},{x:210,y:410},{x:355,y:185},{x:405,y:410},{x:625,y:245},{x:665,y:390},{x:875,y:290},{x:930,y:390}];
async function api(u,o={}){const r=await fetch(u,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o}),d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function guest(){return{id:'guest',name:'Guest Commander',level:1,xp:0,gold:2500,gems:500,summonTokens:10,campaign:1,wave:1,ownedUnits:['ranger','cannon'],ownedChampions:['kendrick','spirit-devourer'],selectedChampion:'kendrick',unitLevels:{ranger:1,cannon:1},championMastery:{kendrick:1000,'spirit-devourer':1000},stats:{battles:0,wins:0,defeats:0,enemiesDefeated:0},daily:{progress:0,target:3,claimed:false}}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2600)}
async function auth(kind,nameEl='#name',passEl='#pass',msgEl='#msg'){const name=$(nameEl).value.trim(),password=$(passEl).value;if(!name||!password){$(msgEl).textContent='Enter your commander name and password.';return}try{const r=await api('/api/account/'+kind,{method:'POST',body:JSON.stringify({name,password})});enter(r.player,false);toast(kind==='login'?'Welcome back, Commander.':'Commander created successfully.')}catch(e){$(msgEl).textContent=e.message}}
function restricted(title){openAuth(title+' is restricted to registered commanders. Create an account or log in to unlock it.')} 
function wire(){
 $('#login').onclick=()=>auth('login');$('#register').onclick=()=>auth('register');$('#guestLogin').onclick=()=>enter(guest(),true);
 $('#closeModal').onclick=closeAuth;$('#guestContinue').onclick=()=>enter(guest(),true);$('#modalLogin').onclick=()=>auth('login','#modalName','#modalPass','#modalMsg');$('#modalRegister').onclick=()=>auth('register','#modalName','#modalPass','#modalMsg');
 $('#accountBtn').onclick=()=>isGuest?openAuth('Create an account to save progress and unlock restricted systems.'):toast(`Logged in as ${player.name}.`);$('#play').onclick=startBattle;
 $('#claim').onclick=async()=>{if(player.daily.progress<3||player.daily.claimed)return;if(isGuest){restricted('Daily rewards');return}player.gold+=500;player.daily.claimed=true;await save();render();toast('500 gold claimed.')};
 $('#summonBtn').onclick=()=>{if(isGuest){restricted('Champion summoning');return}if(player.summonTokens<5)return toast('Not enough summon tokens.');player.summonTokens-=5;$('#stage').innerHTML='<div class="seal">✦</div>';setTimeout(()=>{const id=Math.random()<.5?'kendrick':'spirit-devourer';player.selectedChampion=id;$('#stage').innerHTML=`<div class="reveal"><small>CHAMPION BORN</small><b>${C[id==='spirit-devourer'?'spirit':'kendrick'].name.toUpperCase()}</b><small>MASTERY 1000 · AWAKENED</small></div>`;save();render()},650)};
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
}
function openAuth(t){$('#modal').classList.remove('hidden');$('#modalMsg').textContent='';$('#modalText').textContent=t;$('#modalName').value='';$('#modalPass').value='';$('#modalName').focus()}
function closeAuth(){$('#modal').classList.add('hidden');$('#modalMsg').textContent=''}
function enter(p,g=false){player=p;isGuest=g;if(g)localStorage.removeItem('cf');else localStorage.cf=p.name;closeAuth();$('#auth').classList.add('hide');$('#app').classList.remove('hide');render()}
function render(){if(!player)return;$('#gold').textContent=player.gold.toLocaleString();$('#gems').textContent=player.gems.toLocaleString();$('#tokens').textContent=player.summonTokens.toLocaleString();$('#accountBtn').textContent=isGuest?'GUEST':player.name.toUpperCase();$('#guestNote').textContent=isGuest?'You are browsing as a guest. Battle is available, but your progress cannot be permanently saved.':'Commander account active. Your progress can be saved between sessions.';const c=C[player.selectedChampion==='spirit-devourer'?'spirit':'kendrick'];$('#activeChampion').innerHTML=`<div class="champMini"><div class="icon">${c.icon}</div><b>${c.name}</b><small>MASTERY ${player.championMastery[player.selectedChampion]||1000}</small></div>`;$('#daily').style.width=Math.min(100,player.daily.progress/3*100)+'%';$('#dailyText').textContent=`${Math.min(3,player.daily.progress)} / 3`;$('#claim').disabled=player.daily.progress<3||player.daily.claimed;$('#claim').textContent=player.daily.claimed?'CLAIMED':'CLAIM 500 ◈';$('#units').innerHTML=Object.entries(U).map(([id,u])=>`<article class="unit"><div class="unitIcon">${u.icon}</div><div><h3>${u.name}</h3><p>LEVEL ${player.unitLevels[id]||1} · DAMAGE ${u.d} · RANGE ${u.r} · ${u.rate}s</p><span class="muted">${u.text}</span></div><button>${isGuest?'READY':'UPGRADE'}</button></article>`).join('');$('#champions').innerHTML=Object.entries(C).map(([id,c])=>`<article class="champ"><small>CHAMPION · MASTERY ${player.championMastery[id==='spirit'?'spirit-devourer':'kendrick']||1000}</small><h2>${c.name}</h2><p>${c.text}</p><div class="stats"><div><b>${c.d}</b><span>BASE DAMAGE</span></div><div><b>${c.r}</b><span>RANGE</span></div><div><b>${c.abs.length}</b><span>SPECIALS</span></div></div></article>`).join('');$('#codexGrid').innerHTML=Object.values(E).map(e=>`<div><b>${e.name}</b><span>HP ${e.hp} · SPEED ${e.sp}${e.inv?' · INVISIBLE':''}${e.arm?' · ARMOUR':''}${e.heal?' · HEALER':''}${e.split?' · SPLITTER':''}${e.sum?' · SUMMONER':''}</span></div>`).join('')}
function page(id){if(isGuest&&(id==='collection'||id==='summon')){restricted(id==='collection'?'Collection':'Summoning');return}document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hide',x.id!==id));scrollTo(0,0)}
function startBattle(){$('#app').classList.add('hidden');$('#battle').classList.remove('hidden');battle={ctx:$('#canvas').getContext('2d'),en:[],tw:[],wave:0,gold:player.gold,cit:1000,spawn:0,last:performance.now(),speed:1,pause:false,cd:{},domain:0,combo:0,souls:0,next:false,gameOver:false};$('#deploy').innerHTML=Object.entries(U).map(([id,u])=>`<div class="deploy" data-u="${id}"><b>${u.icon} ${u.name}</b><span>${u.cost} gold · damage ${u.d}</span></div>`).join('');document.querySelectorAll('.deploy').forEach(x=>x.onclick=()=>deploy(x.dataset.u));$('#waveBtn').onclick=wave;$('#speed').onclick=()=>{battle.speed=battle.speed===1?2:1;$('#speed').textContent=battle.speed+'×'};$('#pause').onclick=()=>battle.pause=!battle.pause;$('#back').onclick=endBattle;$('#log').innerHTML='';log(isGuest?'Guest battle started. Progress will not be saved.':'Commander battle started.');updateBattle();drawLoop()}
function endBattle(){battle=null;$('#battle').classList.add('hidden');$('#app').classList.remove('hidden');render()}
function deploy(id){const u=U[id];if(!battle||battle.gameOver||battle.tw.length>=8||battle.gold<u.cost)return toast('Cannot deploy that unit right now.');const s=slots[battle.tw.length];battle.gold-=u.cost;battle.tw.push({...u,x:s.x,y:s.y,t:0});log(`${u.name} deployed.`)}
function wave(){if(!battle||battle.wave>=10)return;if(battle.en.length)return toast('Clear the current wave first.');battle.wave++;battle.next=false;$('#wave').textContent=`WAVE ${battle.wave} / 10`;log(`Wave ${battle.wave} deployed.`)}
function log(t){const d=document.createElement('div');d.textContent=t;$('#log').prepend(d)}
function spawn(){const pool=battle.wave>8?['grunt','runner','brute','wraith','medic','splitter','summoner','elite']:battle.wave>4?['grunt','runner','brute','wraith','medic','splitter']:['grunt','runner','brute'];const k=pool[Math.floor(Math.random()*pool.length)],e=E[k],a=path[0],sc=1+battle.wave*.14;battle.en.push({...e,k,hp:e.hp*sc,max:e.hp*sc,x:a.x,y:a.y,i:0,slow:0})}
function dist(e){let d=0;for(let i=0;i<e.i;i++){const a=path[i],b=path[i+1];d+=Math.hypot(b.x-a.x,b.y-a.y)}return d}
function hurt(e,n){if(e.dead)return;e.hp-=Math.max(1,n-(e.arm||0)*.35);if(e.hp<=0){e.dead=true;battle.gold+=e.rew;player.stats.enemiesDefeated++;if(player.selectedChampion==='spirit-devourer')battle.souls=Math.min(100,battle.souls+Math.max(2,Math.floor(e.rew/8)))}}
function ability(id){if(!battle)return;const now=performance.now();if((battle.cd[id]||0)>now)return;if(id==='annihilation'){battle.cd[id]=now+45000;const m=1+battle.tw.length*.35;battle.en.forEach(e=>!e.dead&&hurt(e,260*m));log('TOTAL ANNIHILATION released.')}if(id==='combo'){battle.cd[id]=now+30000;battle.combo=now+30000;log('PERFECT COMBO — 30 seconds of madness.')}if(id==='transfiguration'){if(battle.souls<20)return toast('Spirit Devourer needs at least 20 souls.');battle.cd[id]=now+5000;battle.domain=now+20000;battle.souls=0;log('IDLE TRANSFIGURATION — 20 second domain activated.')}if(id==='puppeteer'){battle.cd[id]=now+10000;const t=battle.en.filter(e=>!e.dead&&Math.hypot(e.x-520,e.y-300)<180).sort((a,b)=>b.hp-a.hp)[0];if(t){const n=t.hp*.7;hurt(t,n);battle.en.forEach(e=>{if(e!==t&&!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<90)hurt(e,n*.45)});log('PUPPETEER detonated a nearby enemy.')}}}window.useA=ability;
function drawLoop(now=performance.now()){if(!battle)return;const dt=Math.min(.05,(now-battle.last)/1000);battle.last=now;if(!battle.pause&&!battle.gameOver){battle.spawn+=dt*battle.speed;if(battle.wave>0&&battle.spawn>Math.max(.32,1.05-battle.wave*.025)&&battle.en.length<34){battle.spawn=0;spawn()}tick(dt,now)}draw();requestAnimationFrame(drawLoop)}
function tick(dt,now){for(const e of battle.en){if(e.dead)continue;const aura=player.selectedChampion==='spirit-devourer'&&Math.hypot(e.x-520,e.y-300)<150?.35:0,sp=e.sp*(1-aura-(e.slow||0)),a=path[e.i],b=path[e.i+1];if(!b){e.dead=true;battle.cit-=55;continue}const d=Math.hypot(b.x-e.x,b.y-e.y),st=sp*dt*battle.speed;if(d<=st){e.x=b.x;e.y=b.y;e.i++}else{e.x+=(b.x-e.x)/d*st;e.y+=(b.y-e.y)/d*st}}battle.en=battle.en.filter(e=>!e.dead);for(const t of battle.tw){t.t+=dt*battle.speed;if(t.t>=t.rate){const q=battle.en.filter(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<=t.r).sort((a,b)=>dist(b)-dist(a))[0];if(q){t.t=0;hurt(q,t.d*(battle.domain>now?10:1));if(t.name==='Cannon')battle.en.forEach(e=>{if(e!==q&&!e.dead&&Math.hypot(e.x-q.x,e.y-q.y)<55)hurt(e,t.d*.35)})}}}if(now%1000<45){const c=C[player.selectedChampion==='spirit-devourer'?'spirit':'kendrick'],q=battle.en.find(e=>!e.dead&&Math.hypot(e.x-520,e.y-300)<c.r);if(q)hurt(q,c.d*(battle.domain>now?10:1))}if(player.selectedChampion==='kendrick'&&battle.combo>now&&Math.random()<.12)battle.en.slice(0,3).forEach(e=>hurt(e,120));if(battle.wave>0&&battle.en.length===0&&battle.spawn<.2&&!battle.next){battle.next=true;log(`Wave ${battle.wave} cleared.`);if(battle.wave>=10)finish(true)}if(battle.cit<=0)finish(false);updateBattle()}
function finish(win){if(battle.gameOver)return;battle.gameOver=true;player.stats.battles++;if(win){player.stats.wins++;player.daily.progress=Math.min(3,player.daily.progress+1);player.gold+=500;toast('VICTORY — 500 gold awarded.')}else{player.stats.defeats++;toast('DEFEAT — reinforce and try again.')}battle.gold=player.gold;if(!isGuest)save()}
function updateBattle(){if(!battle)return;$('#bgold').textContent=Math.floor(battle.gold);$('#hp').textContent=Math.max(0,Math.floor(battle.cit));$('#soulBar').classList.toggle('hidden',player.selectedChampion!=='spirit-devourer');$('#soulFill').style.width=battle.souls+'%';$('#soulText').textContent=`${battle.souls} / 100`;renderAbilities()}
function renderAbilities(){if(!battle)return;const key=player.selectedChampion==='spirit-devourer'?'spirit':'kendrick',c=C[key],now=performance.now();$('#abilities').innerHTML=`<div class="abilities">${c.abs.map(a=>{const left=Math.max(0,Math.ceil(((battle.cd[a[0]]||0)-now)/1000));return `<button class="ability" onclick="window.useA('${a[0]}')"><b>${a[1]}</b><span>${left?left+'s':'READY'} · ${key==='spirit'?(a[0]==='transfiguration'?'20s domain · 20+ souls':'10s HP-scaled explosion'):(a[0]==='combo'?'30s chain lightning':'Thunder-wave · ally scaling')}</span></button>`}).join('')}</div>`}
function draw(){const c=battle.ctx;c.clearRect(0,0,1100,620);c.fillStyle='#080c12';c.fillRect(0,0,1100,620);c.strokeStyle='#111b28';for(let x=0;x<1100;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,620);c.stroke()}for(let y=0;y<620;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(1100,y);c.stroke()}c.strokeStyle='#293445';c.lineWidth=48;c.beginPath();c.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>c.lineTo(p.x,p.y));c.stroke();c.strokeStyle='#171f2c';c.lineWidth=34;c.beginPath();c.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>c.lineTo(p.x,p.y));c.stroke();for(const s of slots){c.strokeStyle='#344258';c.strokeRect(s.x-22,s.y-22,44,44)}for(const t of battle.tw){c.fillStyle=t.name==='Cannon'?'#ffb347':'#72e7ff';c.beginPath();c.arc(t.x,t.y,18,0,7);c.fill();c.fillStyle='#111';c.fillText(t.icon,t.x-6,t.y+4)}const sc=C[player.selectedChampion==='spirit-devourer'?'spirit':'kendrick'];c.strokeStyle=player.selectedChampion==='spirit-devourer'?'#c66cff77':'#ffb34777';c.beginPath();c.arc(520,300,sc.r,0,7);c.stroke();if(player.selectedChampion==='spirit-devourer'&&battle.domain>performance.now()){c.fillStyle='#c66cff13';c.beginPath();c.arc(520,300,190,0,7);c.fill();c.strokeStyle='#d87bff99';c.stroke()}c.fillStyle='#ffb347';c.beginPath();c.arc(520,300,25,0,7);c.fill();for(const e of battle.en){c.fillStyle=e.inv?'#7770a888':'#bd7880';c.beginPath();c.arc(e.x,e.y,Math.max(7,Math.min(17,7+e.max/350)),0,7);c.fill();c.fillStyle='#ff6479';c.fillRect(e.x-15,e.y-23,30,3);c.fillStyle='#7cf0b0';c.fillRect(e.x-15,e.y-23,30*Math.max(0,e.hp/e.max),3)}}
wire();enter(guest(),true);(async()=>{if(localStorage.cf){try{enter((await api('/api/player/'+encodeURIComponent(localStorage.cf))).player,false);toast('Saved commander restored.')}catch{localStorage.removeItem('cf')}}})();
